codecov:
  token: "d5afce92-dfc9-486a-8744-97db7b0baf4e"

coverage:
  status:
    project:
      default:
        threshold: 10%
    patch:
      default:
        threshold: 10%

fixes:
  - "/**/21s2-cp-spa-team-32/21s2-cp-spa-team-32/::"