name: Compile and Test - Self Hosted
on: [push, pull_request]

env:
  BUILD_TYPE: Coverage

jobs:
  runner-job:
    runs-on: [self-hosted, macOS, x64]
    steps:
      - name: Cleanup workspace
        shell: bash
        run: rm -rf ${{github.workspace}}/* && rm -rf {{runner.workspace}}/build

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Create build environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake ${{github.workspace}}/Team32/Code32/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --parallel 8

      - name: Run unit tests
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ./src/unit_testing/unit_testing

      - name: Run integration tests
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ./src/integration_testing/integration_testing
