name: Lint Checks
on: [pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Coverage

jobs:
  lint-checks:
    runs-on: macos-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Run format check
        shell: bash
        working-directory: ${{github.workspace}}/Team32/Code32
        run: clang-format -style=file -Werror --dry-run src/spa/src/**/*

      - name: Create build environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake ${{github.workspace}}/Team32/Code32/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Run lint
        shell: bash
        working-directory: ${{github.workspace}}/Team32/Code32
        run: clang-tidy -p ${{runner.workspace}}/build ./src/spa/src/**/*.cpp ./src/spa/src/**/*.h